var data = {
  "Sheet1": [
   {
     "First Name": "Indigo",
     "Last Name": "Brownhall",
     "Role": "Outreach Lead",
     "About": "Indigo Brownhall is currently working at Gather, part of the geospatial team, they are aiming to build a geospatial sanitation risk index, in order to get toilets to those who need them most. He originally started his mapping career at Durham University, and is currently studying an MSc in Geospatial Sciences (GIS and Computing) at UCL.",
     "Currently Reading": "The Age of Surveillance Capitalism by Shoshana Zuboff‎",
     "Favourite Band": "Skinshape",
     "Outside Work": "Travelling, Cycling and Computer Gaming",
     "lat": 50.626042,
     "lng": -3.98029,
     "Manager": 1
   },
   {
     "First Name": "Josh",
     "Last Name": "Wilson",
     "Role": "GIS Manager",
     "About": "Josh holds a Geography BSc from Durham University and is currently enrolled at University College London for an MSc in ‘Risk, Disasters and Resilience’. Using his strong background in GIS skills, Josh is interested in using spatial data to quantify risk in areas such as landslides, flooding and sanitation.",
     "Currently Reading": "A short history of nearly everything, by Bill Bryson",
     "Favourite Band": "Tame Impala",
     "Outside Work": "Yoga",
     "lat": 51.469137,
     "lng": -0.162458,
     "Manager": 1
   },
   {
     "First Name": "Ed",
     "Last Name": "Beddows",
     "Role": "Co-Founder",
     "About": "Ed holds a Geography BSc from Durham University and has completed the SDG Academy Course on Environmental Security and Sustaining Peace. With a large focus on interdisciplinary research, he specialises in environmental change, management and conservation. Within this, he uses a range of remote sensing and modelling software.",
     "Currently Reading": "Kon-Tiki, by Thor Hererdahl",
     "Favourite Band": "The Juju Exchange",
     "Outside Work": "Adventure sports enthusiast (skiing, hiking), Hockey, Singing",
     "lat": 52.808922,
     "lng": -0.722643,
     "Manager": 1
   },
   {
     "First Name": "Grachen",
     "Last Name": "Oneko",
     "Role": "GIS Manager",
     "About": "Grachen works closesly with the volunteers, ensuring that projects are met on time, whilst also liasing with the clients and charities to ensure their standards are met. Grachen has recently won GIS-E employee of the month!",
     "Currently Reading": "Prisoners of Geography by Tim Marshall",
     "Favourite Band": "ABBA",
     "Outside Work": "Travelling",
     "lat": 51.896808,
     "lng": 4.768862,
     "Manager": 1
   },
   {
     "First Name": "Tom",
     "Last Name": "Bugler",
     "Role": "Co-Founder",
     "About": "Tom holds a Geography BSc from Durham University. Specialising in remote sensing and GIS, his research was focused on hazard risk reduction in mountain landscapes and the impacts of climate change on the Cryosphere.",
     "Currently Reading": "The AI does not hate you. Superintelligence, rationality and the race to save the world, by Tom Chivers",
     "Favourite Band": "Tedeschi Trucks Band",
     "Outside Work": "Rowing, Running, Guitar",
     "lat": 51.39198,
     "lng": -1.500292,
     "Manager": 1
   },
   {
     "First Name": "Tristan ",
     "Last Name": "Willis",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 52.324684,
     "lng": -2.298385,
     "Manager": 0
   },
   {
     "First Name": "Samuel",
     "Last Name": "Akinnusi",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 7.337222,
     "lng": 7.319005,
     "Manager": 0
   },
   {
     "First Name": "Iniobong",
     "Last Name": "Benson",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 10.307029,
     "lng": 11.365874,
     "Manager": 0
   },
   {
     "First Name": "Rosie",
     "Last Name": "Beddows",
     "Role": "Partnerships Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 54.984319,
     "lng": -1.590643,
     "Manager": 0
   },
   {
     "First Name": "Zach ",
     "Last Name": "Pescod-Everiss",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 51.425582,
     "lng": -0.086145,
     "Manager": 0
   },
   {
     "First Name": "Anna",
     "Last Name": "Latham",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 51.788179,
     "lng": -1.075533,
     "Manager": 0
   },
   {
     "First Name": "Connie ",
     "Last Name": "Harper",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 54.691952,
     "lng": -1.514137,
     "Manager": 0
   },
   {
     "First Name": "Euclides ",
     "Last Name": "Paulo",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": -9.134809,
     "lng": 13.23076,
     "Manager": 0
   },
   {
     "First Name": "Enesa",
     "Last Name": "Luta",
     "Role": "Social Media Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 51.401056,
     "lng": -0.07541,
     "Manager": 0
   },
   {
     "First Name": "Rahamandhika",
     "Last Name": "Tri Puta",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": -6.2938,
     "lng": 106.62546,
     "Manager": 0
   },
   {
     "First Name": "Opeyemi",
     "Last Name": "Kazeem-Jimoh",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 9.596973,
     "lng": 6.652987,
     "Manager": 0
   },
   {
     "First Name": "Madeleine",
     "Last Name": "Champion",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 54.691952,
     "lng": -1.514137,
     "Manager": 0
   },
   {
     "First Name": "Taiwo ",
     "Last Name": "Ogunwumi",
     "Role": "GIS Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 5.76523,
     "lng": 5.996334,
     "Manager": 0
   },
   {
     "First Name": "Harrison",
     "Last Name": "Luft ",
     "Role": "Outreach Volunteer",
     "About": "",
     "Currently Reading": "",
     "Favourite Band": "",
     "Outside Work": "",
     "lat": 40.566859,
     "lng": -122.363217,
     "Manager": 0
   }
  ]
  }
